"""empty message

Revision ID: 398ac1e519b6
Revises: 
Create Date: 2024-03-04 17:58:17.551495

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '398ac1e519b6'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('board',
    sa.Column('board_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('board_title', sa.String(), nullable=True),
    sa.Column('board_contents', sa.String(), nullable=True),
    sa.Column('writer', sa.String(), nullable=True),
    sa.Column('create_date', sa.Date(), nullable=True),
    sa.Column('views', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('board_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('board')
    # ### end Alembic commands ###
